use `unknown` icon when one is not available
nwg-piotr/nwg-drawer pull request #27
Opened 2021-09-22 11:52 UTC by aajonusonline

Here is behavior with missing icons in the theme in before this patch:
![image](https://user-images.githubusercontent.com/62964550/134338624-2969fcd4-9493-4c45-a6b7-44f8743b8044.png)

Here is behavior with this patch:
![image](https://user-images.githubusercontent.com/62964550/134338653-9bb5b7f6-c613-4faf-981b-bbd50fc2842b.png)

2021-09-22 12:11 UTC, nwg-piotr requested changes
Is there a need for a new function? IMO modifying the `createPixbuf` function would be enough.

2021-09-22 15:11 UTC, aajonusonline commented
> Is there a need for a new function? IMO modifying the `createPixbuf` function would be enough.

There is no **need** for it, but it uses the same (somewhat obscure) piece of code twice, if you don't like it - can be changed back.

2021-09-22 21:06 UTC, nwg-piotr approved these changes

2021-09-22 21:09 UTC, nwg-piotr commented
In case you had more fixes to this project: hold on for awhile, until `v02` is ready and merged.

2021-09-22 21:09 UTC, merged

2021-09-23 12:51 UTC, aajonusonline commented
> In case you had more fixes to this project: hold on for awhile, until `v02` is ready and merged.

I hope you would also add a nwg-drawer-bin package to AUR, since repo has a bin folder with a binary file, and compiling the whole thing for the first time takes ages

2021-09-23 13:22 UTC, nwg-piotr commented
Initially I planned to publish the -bin package only, but some people advised me not to. What discourages me from having 2 packages per program, is the fact, that I already have 19 packages to maintain.