Fix high CPU load
nwg-piotr/nwg-drawer pull request #53
Opened 2022-02-13 22:35 UTC by Raffy23

This PR fixes #50 by using a channel instead of a boolean flag that is polled in a fixed interval.
Currently all updates done by the file watcher will only be applied before displaying the window, which wasn't the case before, but I think it is still sufficient for the current usecase.

2022-02-13 23:14 UTC, nwg-piotr requested changes
Works as expected, but partially breaks pinned items: the pinned flowbox is not being refreshed. Also, when running residently, after pinning a file, the windows does not show up at first try.

2022-02-14 19:44 UTC, Raffy23 commented
I wasn't aware of this feature and it seems like a regression that can be fixed by handling the `pinnedTrigger` in a similar way as it is the case with the signals. With this patch the window needs to be closed and reopened for the changes to appear.
Maybe it would also be a good idea to handle the pinned items differently without destroying & recreating the container for the buttons, but I think that should be part of a different issue / PR.

2022-02-14 23:30 UTC, nwg-piotr approved these changes

2022-02-14 23:34 UTC, nwg-piotr commented
> Maybe it would also be a good idea to handle the pinned items differently without destroying & recreating the container for the buttons

Setting a filter function would be the natural way, but it's not implemented in gotk3. In this use case it has little to none effect on overall performance, so I don't care.

2022-02-14 23:37 UTC, merged